version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
      - db
      - mailhog
      - phpmyadmin
    networks:
      - laravel

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ewallet
      MYSQL_USER: ewalletuser
      MYSQL_PASSWORD: ewalletpw
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - laravel

  php:
    image: php:7.4-fpm-alpine:latest
    container_name: php
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - MYSQL_USER=ewalletuser
      - MYSQL_PASSWORD=ewalletpw
      - MYSQL_ROOT_PASSWORD=root
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=2G
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel
